<a href="https://colab.research.google.com/github/saykim/pyML/blob/master/seaborn_loaddata.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd, numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import tensorflow as tf

from keras.models import Sequential
from keras.layers import Dense
from keras.utils import np_utils
from sklearn.preprocessing import LabelEncoder



In [0]:
diamond = sns.load_dataset('diamonds')

In [9]:
diamond.head()

carat      cut color clarity  depth  table  price     x     y     z
0   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3   0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4   0.31     Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75

In [11]:
diamond.tail()

carat        cut color clarity  depth  table  price     x     y     z
53935   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53936   0.72       Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86    Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

In [0]:
dataset = diamond.values

In [0]:
X = dataset[:,:6]
Y_obj = dataset[:,6]

In [0]:
e = LabelEncoder()
y1 = e.fit_transform(Y_obj)
Y=pd.get_dummies(y1).values


In [0]:
e = LabelEncoder()
diamond['cut'] = e.fit_transform(diamond['cut'])
diamond['clarity'] = e.fit_transform(diamond['clarity'])


In [0]:
diamond['color'] = e.fit_transform(diamond['color'])

In [19]:
diamond.head()

carat  cut  color  clarity  depth  table  price     x     y     z
0   0.23    2      1        3   61.5   55.0    326  3.95  3.98  2.43
1   0.21    3      1        2   59.8   61.0    326  3.89  3.84  2.31
2   0.23    1      1        4   56.9   65.0    327  4.05  4.07  2.31
3   0.29    3      5        5   62.4   58.0    334  4.20  4.23  2.63
4   0.31    1      6        3   63.3   58.0    335  4.34  4.35  2.75

In [0]:
from sklearn.model_selection import  train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X, Y_obj, test_size=0.3, random_state=42)


In [33]:
model = Sequential()
model.add(Dense(30, input_dim=6, activation='relu'))
model.add(Dense(6, activation='relu'))
model.add(Dense(1))

model.compile(loss='mean_squared_error', optimizer='adam')
model.fit(X_train, Y_train, epochs=200, batch_size=10)

Epoch 1/200
37758/37758 [==============================] - 11s 279us/step - loss: 31651357.1906
Epoch 2/200
37758/37758 [==============================] - 10s 270us/step - loss: 31622763.5416
Epoch 3/200
37758/37758 [==============================] - 11s 282us/step - loss: 31594386.7500
Epoch 4/200
37758/37758 [==============================] - 10s 276us/step - loss: 31566056.5207
Epoch 5/200
37758/37758 [==============================] - 10s 270us/step - loss: 31537731.4400
Epoch 6/200
37758/37758 [==============================] - 10s 270us/step - loss: 31509525.4791
Epoch 7/200
37758/37758 [==============================] - 10s 271us/step - loss: 31481307.3542
Epoch 8/200
37758/37758 [==============================] - 10s 264us/step - loss: 31453145.5753
Epoch 9/200
37758/37758 [==============================] - 10s 264us/step - loss: 31424924.3412
Epoch 10/200
37758/37758 [==============================] - 10s 265us/step - loss: 31396785.6608
Epoch 11/200
37758/37758 [=============

In [26]:
print(model.evaluate(X,Y_obj)[1])

53940/53940 [==============================] - 2s 35us/step
0.0


In [27]:
X

array([[ 0.23,  2.  ,  1.  ,  3.  , 61.5 , 55.  ],
       [ 0.21,  3.  ,  1.  ,  2.  , 59.8 , 61.  ],
       [ 0.23,  1.  ,  1.  ,  4.  , 56.9 , 65.  ],
       ...,
       [ 0.7 ,  4.  ,  0.  ,  2.  , 62.8 , 60.  ],
       [ 0.86,  3.  ,  4.  ,  3.  , 61.  , 58.  ],
       [ 0.75,  2.  ,  0.  ,  3.  , 62.2 , 55.  ]])

In [29]:
Y_obj

array([ 326.,  326.,  327., ..., 2757., 2757., 2757.])

In [30]:
diamond['cut'].unique()

array([2, 3, 1, 4, 0])