In [1]:
import tensorflow as tf

In [2]:
x_train = [1,2,3]
y_train = [1,2,3]

W = tf.Variable(tf.random_normal([1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

hypothesis = x_train * W + b

In [3]:
cost = tf.reduce_mean(tf.square(hypothesis - y_train))

In [4]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.01)
train = optimizer.minimize(cost)

In [5]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [7]:
for step in range(3001):
    sess.run(train)
    if step % 100 == 0:
        print(step, sess.run(cost), sess.run(W), sess.run(b))

0 0.0038731827 [0.927718] [0.16431384]
100 0.002393396 [0.9431798] [0.12916571]
200 0.0014789696 [0.9553341] [0.10153601]
300 0.00091391086 [0.9648886] [0.07981649]
400 0.00056474196 [0.9723993] [0.06274301]
500 0.0003489734 [0.97830325] [0.04932163]
600 0.00021564553 [0.9829444] [0.03877134]
700 0.00013325721 [0.9865927] [0.03047785]
800 8.234411e-05 [0.9894605] [0.02395841]
900 5.0884246e-05 [0.99171513] [0.01883356]
1000 3.1443156e-05 [0.99348736] [0.01480479]
1100 1.9430516e-05 [0.9948804] [0.01163793]
1200 1.2006389e-05 [0.9959756] [0.00914846]
1300 7.419101e-06 [0.9968364] [0.00719148]
1400 4.5847196e-06 [0.9975132] [0.00565319]
1500 2.8330926e-06 [0.9980451] [0.00444398]
1600 1.7507201e-06 [0.9984632] [0.00349339]
1700 1.0819538e-06 [0.99879193] [0.0027462]
1800 6.685711e-07 [0.99905026] [0.00215885]
1900 4.1321255e-07 [0.99925333] [0.00169718]
2000 2.554311e-07 [0.999413] [0.00133429]
2100 1.578435e-07 [0.99953854] [0.00104902]
2200 9.757978e-08 [0.9996372] [0.00082482]
2300 6.

## Placeholder

In [28]:
import tensorflow as tf

W = tf.Variable(tf.random_normal([1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name ='bias')
X = tf.placeholder(tf.float32, shape=[None]) #hypothesis변수 확인
Y = tf.placeholder(tf.float32, shape=[None]) #cost변수 확인

hypothesis = X * W + b

cost = tf.reduce_mean(tf.square(hypothesis - Y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.01)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

#측정이 필요한 값을 직접 입력
for step in range(2001):
    cost_val, W_val, b_val, _ = sess.run([cost, W, b, train], feed_dict={X:[1,2,3,4,5], Y:[4,8,12,16,20]})
    if step % 200 == 0:
        print(step, cost_val, W_val, b_val)

## multi-variable linear regression

In [1]:
import tensorflow as tf

In [3]:
x_data = [[73., 80.,75], [93.,88.,93.],[89.,91.,90.],[96.,98.,100],[73.,66.,70.]]
y_data = [[152.],[185.],[180.],[196.],[142.]]

# placeholder for a tensor that will be always fed.

X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3,1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

#Hypothesis

hypothesis = tf.matmul(X,W) + b

cost = tf.reduce_mean(tf.square(hypothesis - Y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict={X:x_data, Y:y_data})
    if step % 500 == 0:
        print(step, 'Cost: ', cost_val, '\nPrediction: \n', hy_val)


0 Cost:  76055.86 
Prediction: 
 [[ -91.93518]
 [-110.16585]
 [-108.56682]
 [-120.69072]
 [ -81.80408]]
500 Cost:  0.90217364 
Prediction: 
 [[152.69662]
 [183.99086]
 [181.20287]
 [194.88937]
 [142.5717 ]]
1000 Cost:  0.8667717 
Prediction: 
 [[152.63568]
 [184.03069]
 [181.18167]
 [194.89339]
 [142.60767]]
1500 Cost:  0.83639276 
Prediction: 
 [[152.58145]
 [184.06593]
 [181.16258]
 [194.89865]
 [142.63783]]
2000 Cost:  0.80989206 
Prediction: 
 [[152.53307]
 [184.09717]
 [181.14531]
 [194.90503]
 [142.66295]]


## loading DATA

import numpy as np
import tensorflow as tf

xy = np.loadtxt('data-01-test-score.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:,[-1]]

X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3,1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.matmul(X,W)+ b

cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(5001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict={X:x_data, Y:y_data})
    if step % 1000 == 0:
        print(step, 'Cost: ', cost_val, '\nPrediction: \n', hy_val)


### 다른 사람 성적 예측

In [23]:
print('You score will be', sess.run(hypothesis, feed_dict={X:[[100,70, 101]]}))
print('Other score will be', sess.run(hypothesis, feed_dict={X:[[60,70,110], [90,100,80]]}))

You score will be [[193.0142]]
Other score will be [[175.95093]
 [174.30179]]


# 데이터가 너무 많아서 numpy 에 로드가 안될때

> Queue Runner